; This is your project configuration file. It tells PlatformIO which board you are using, 
; which framework to compile with, and what external sensor libraries to automatically download from the internet.


[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    claws/BH1750 @ ^1.3.0
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    milesburton/DallasTemperature @ ^3.11.0
    paulstoffregen/OneWire @ ^2.3.8



; [env:esp32doit-devkit-v1]
; platform = espressif32
; board = esp32doit-devkit-v1
; framework = arduino
; monitor_speed = 115200